V1.2 delete important dates
AY2324S2-CS2103-F09-2/tp pull request #65
Opened 2024-03-14 15:57 UTC by ZhiWei1010

This commit allows for important dates to be deleted for patients.

- Add new DeleteImportantDateCommand
- Add new DeleteImportantDateParser

To be done:  
- [ ] format of command
- [ ] testing

2024-03-14 16:23 UTC, NeoHW requested changes
consider design and additional changes

2024-03-14 16:23 UTC, NeoHW commented on src/main/java/seedu/address/logic/commands/DeleteImportantDateCommand.java
> +    public static final String COMMAND_WORD = "deleteID";
could consider following naming convention 
e.g. adding important dates : `adde`
can consider something similar to `deletee`?

2024-03-14 16:23 UTC, NeoHW commented on src/main/java/seedu/address/logic/commands/DeleteImportantDateCommand.java
> +    public static final String MESSAGE_DELETE_IMPORTANT_DATE_SUCCESS = "Deleted Important Dates for Patient: %1$s";
Deleting one date: Delete Important Date~s~

2024-03-14 16:23 UTC, NeoHW commented on src/main/java/seedu/address/logic/parser/AddressBookParser.java
> +
Extra line?

2024-03-14 16:23 UTC, NeoHW commented on src/main/java/seedu/address/logic/parser/CliSyntax.java
> +    public static final Prefix PREFIX_IMPORTANT_DATE = new Prefix("e/");
it might be confusing for user to have adding of ID be n/ d/ 
then introduce deleting to use e/

2024-03-15 06:00 UTC, ZhiWei1010 commented on src/main/java/seedu/address/logic/commands/DeleteImportantDateCommand.java
> +    public static final String MESSAGE_DELETE_IMPORTANT_DATE_SUCCESS = "Deleted Important Dates for Patient: %1$s";
Good catch! Fixed.

2024-03-15 06:11 UTC, ZhiWei1010 commented on src/main/java/seedu/address/logic/parser/AddressBookParser.java
> +
Good Catch. Fixed

2024-03-15 06:13 UTC, ZhiWei1010 commented on src/main/java/seedu/address/logic/parser/CliSyntax.java
> +    public static final Prefix PREFIX_IMPORTANT_DATE = new Prefix("e/");
The idea is for user to quickly delete the event via event ID instead of typing the whole date to delete, so I think this is fine. It is also consistent with the convention of adding important date 'adde'. Should be ok for user to learn this. Could be discussed further with input from others!

2024-03-15 06:19 UTC, ZhiWei1010 commented on src/main/java/seedu/address/logic/commands/DeleteImportantDateCommand.java
> +    public static final String COMMAND_WORD = "deleteID";
Changed command to {@code deletee}

2024-03-15 14:03 UTC, choowengyan approved these changes
LGTM!

2024-03-15 18:16 UTC, NeoHW approved these changes
code lgtm, ui tested and working

2024-03-15 18:16 UTC, merged